// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2YCsudAPErQ1cg-uIYBXs48gJgy_lcuA',
    appId: '1:816395930545:web:358d887db75bdef4d6cb90',
    messagingSenderId: '816395930545',
    projectId: 'btrack-9d879',
    authDomain: 'btrack-9d879.firebaseapp.com',
    storageBucket: 'btrack-9d879.appspot.com',
    measurementId: 'G-LPLV7GVBFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHwkCGXBDR-BYjBPNMVFUj5T3gbQNm-YM',
    appId: '1:816395930545:android:0903c91901c1de1bd6cb90',
    messagingSenderId: '816395930545',
    projectId: 'btrack-9d879',
    storageBucket: 'btrack-9d879.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk1iFt6C9dNWaQ_hj3ijARcYtTfClUziY',
    appId: '1:816395930545:ios:50be8edec4e036e4d6cb90',
    messagingSenderId: '816395930545',
    projectId: 'btrack-9d879',
    storageBucket: 'btrack-9d879.appspot.com',
    iosBundleId: 'com.example.budget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk1iFt6C9dNWaQ_hj3ijARcYtTfClUziY',
    appId: '1:816395930545:ios:50be8edec4e036e4d6cb90',
    messagingSenderId: '816395930545',
    projectId: 'btrack-9d879',
    storageBucket: 'btrack-9d879.appspot.com',
    iosBundleId: 'com.example.budget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2YCsudAPErQ1cg-uIYBXs48gJgy_lcuA',
    appId: '1:816395930545:web:ab010f343679d97cd6cb90',
    messagingSenderId: '816395930545',
    projectId: 'btrack-9d879',
    authDomain: 'btrack-9d879.firebaseapp.com',
    storageBucket: 'btrack-9d879.appspot.com',
    measurementId: 'G-EJR19BGEB1',
  );
}
